### PR TITLE
code cleanup to make it more readable

### PR DESCRIPTION
**Pull request by jfrede**
Code looked like someone has copied everything together from different sources. 
I've tried to make it a bit more readable and rewrote some things like a funktion to blink LEDs which was written several times in the code.  
I've also set the speed for CAT to 9600 baud because 115200 is not allowed for TS-2000 in the newer Hamlib releases.

### CODE REVIEW

**Comment by WB2CBA** [comment]
Hi Joerg,Thank you for refining and clearing my cluttered code. Much appreciated. I tried your code this weekend and it works though on FT4 there is a TX problem. The TX is there and transmitting though it does not register on pskreporter. I didn’t have time to go through code to check. When I upload V1.4 code to same adx no problem in FT4. I did my test on 20m/14 mhz band only with CAT.73Barb WB2CBAOn Apr 29, 2023, at 06:08, Joerg Frede ***@***.***> wrote:﻿Code looked like someone has copied everything together from different sources.
I've tried to make it a bit more readable and rewrote some things like a funktion to blink LEDs which was written several times in the code.
I've also set the speed for CAT to 9600 baud because 115200 is not allowed for TS-2000 in the newer Hamlib releases.



You can view, comment on, or merge this pull request online at:
  https://github.com/WB2CBA/ADX/pull/1

Commit Summary

  9e08ab2  code cleanup to make it more readable


File Changes  (2 files)

  
    D
    ADX FIRMWARE/ADX_CAT_V1.4.ino
    (1176)
  
  
    A
    ADX FIRMWARE/ADX_CAT_V1.5.ino
    (845)
  


Patch Links:

  https://github.com/WB2CBA/ADX/pull/1.patch
  https://github.com/WB2CBA/ADX/pull/1.diff

**Comment by jfrede** [comment]
It was time to look at it today. Problem was that somewhere lost a ULL and thus the TX frequency was not correct.

**Comment by WB2CBA** [comment]
Joerg,Thank you for cleaning up the code and fixing that issue. I merged your code to adx github. Your code V1.5 is the official ADX code now.Thank you!On Jun 9, 2023, at 08:14, Joerg Frede ***@***.***> wrote:﻿
It was time to look at it today. Problem was that somewhere lost a ULL and thus the TX frequency was not correct.

**Comment by jfrede** [comment]
There still seems to be a problem that the TX is off by -4KHz from time to time. I also have this with your code.

**Comment by jfrede** [comment]
You can ignore my last comment i got fouled by my upconverter.

**Pull request merged**
